// Code generated by mockery v1.0.0
package mocks

import backend "confd-template/backend"
import mock "github.com/stretchr/testify/mock"
import template "confd-template/template"

// Backend is an autogenerated mock type for the Backend type
type Backend struct {
	mock.Mock
}

// Keys provides a mock function with given fields: _a0
func (_m *Backend) Keys(_a0 *template.Template) chan *backend.Key {
	ret := _m.Called(_a0)

	var r0 chan *backend.Key
	if rf, ok := ret.Get(0).(func(*template.Template) chan *backend.Key); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *backend.Key)
		}
	}

	return r0
}
